version: "3"

services:
  app:
    image: ruby:3.0.2
#    environment:
#      TOGODX_SERVER_DATABASE_HOST: db
#      TOGODX_SERVER_DATABASE_PASSWORD:
    command: bash -c "bundle install && rm -f tmp/pids/server.pid && rails s -b '0.0.0.0'"
    volumes:
      - .:/app
      - app_bundle:/usr/local/bundle
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - db

#  db:
#    image: postgres:13.4
#    environment:
#      POSTGRES_USER: togodx_server
#      POSTGRES_PASSWORD:
#    volumes:
#      - db_data:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"

volumes:
  app_bundle:
#  db_data:
