version: "3"

services:
  nginx:
    image: nginx:1.21
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - app_sockets:/tmp/sockets:ro
    ports:
      - "${NGINX_PORT:-80}:80"
    depends_on:
      - app
    <<: &logging
      logging:
        driver: "json-file"
        options:
          max-size: "1m"
          max-file: "1"

  app:
    image: ruby:3.0.2
    environment:
      RAILS_ENV: production
      RAILS_MAX_THREADS: 10
      WEB_CONCURRENCY: 10
    env_file:
      - ../.env
    command: bash -c "bundle install && rm -f tmp/pids/server.pid && rails s -b '0.0.0.0'"
    volumes:
      - .:/app
      - app_bundle:/usr/local/bundle
      - app_sockets:/app/tmp/sockets
    working_dir: /app
    depends_on:
      - db
    <<: *logging

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-togodx}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-changeme}"
    volumes:
      - ./data/pg_data:/var/lib/postgresql/data
      - ./docker/postgres/postgres.conf:/etc/postgresql/postgresql.conf:ro
    <<: *logging

volumes:
  app_bundle:
  app_sockets:
