version: "3"

services:
  app:
    image: ruby:3.0.2
    command: bash -c "bundle install && rm -f tmp/pids/server.pid && rails s -b '0.0.0.0'"
    volumes:
      - .:/app
      - app_bundle:/usr/local/bundle
    working_dir: /app
    ports:
      - "${APP_PORT:-3000}:3000"
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-togodx}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-changeme}"
    volumes:
      - ./tmp/pg_data:/var/lib/postgresql/data
      - ./docker/postgres/postgres.conf:/etc/postgresql/postgresql.conf:ro

volumes:
  app_bundle:
